name: Release Docker Images
on:
  workflow_call:
    secrets:
      GHCR_IO_TOKEN:
        description: "GHCR_IO_TOKEN"
        required: true
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to docker ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: USERNAME
          password: ${{ secrets.GHCR_IO_TOKEN }}
      - name: Docker smtprelay meta
        id: smtprelay
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - name: Build  and push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.smtprelay.outputs.tags }}
          labels: ${{ steps.smtprelay.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            GITHUB_REPOSITORY=${{ github.repository }}
            APP_VERSION=${{ github.ref_name }}
