name: Release Docker Images
on:
  workflow_call:
    secrets:
      GHCR_IO_TOKEN:
        description: "GHCR_IO_TOKEN"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: dump release
        run: |
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
          echo ${{ github.ref_name }}
          echo ${{ github.event.release.name }}
          echo ${{ github.event.release.tag_name }}
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: Login to docker ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: USERNAME
          password: ${{ secrets.GHCR_IO_TOKEN }}
      - name: Docker smtprelay meta
        id: smtprelay
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - name: Build  and push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.smtprelay.outputs.tags }}
          labels: ${{ steps.smtprelay.outputs.labels }}
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          build-args: |
            REPOSITORY_OWNER=${{ github.repository_owner }}
            APP_VERSION=${{ github.ref_name }}
            
            
      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}